apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: cnpg
spec:
  instances: 3
  #imageName: ghcr.io/cloudnative-pg/postgresql:14.5
  #imagePullPolicy: Always
  minSyncReplicas: 1
  maxSyncReplicas: 1

  # Reduce the frequency of standby HA slots updates to once every 5 minutes
  replicationSlots:
    highAvailability:
      enabled: true

  postgresql:
    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      #timezone: "Europe/Amsterdam"

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  backup:
    #target: "prefer-standby"
    barmanObjectStore:
      wal:
        maxParallel: 8
      destinationPath: "https://st8001xplanetesting.blob.core.windows.net/kastencontainer/kastenblob"
      azureCredentials:
        storageAccount:
          name: azure-creds
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          name: azure-creds
          key: AZURE_STORAGE_KEY
      data:
        immediateCheckpoint: true
      #wal:
      #  compression: gzip
      #  maxParallel: 8
      #  encryption: AES256
    retentionPolicy: "1d"
